[package]
name = "webgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
terp = { path = "../" }
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1.1", optional = true }

[lib]
crate-type = ["cdylib"]
